"""
docx_report.py — generate the Contract Workspace Summary document for one
contract, using the team's own template
(assets/Contract_Workspace_Summary_Template.docx) as the base, with its
placeholder Lorem Ipsum content replaced by real extracted values. Same
headings, same tables, same styles — nothing rebuilt from scratch, so
formatting changes the team makes to the template file itself carry
through automatically.

LEX-specific: not part of the generic project-llm-wiki template.

Structural layout the template is assumed to have (confirmed directly
against the file bundled in assets/ — see this module's own test in the
repo history if the template is ever replaced):

    Title paragraph                              "<Supplier> - <Services>"
    Subtitle paragraph                            (left as-is)
    Table: "Contract detail" / "Current position" (5 data rows, col 1)
    Heading 1: "Executive Assessment"
      body paragraph                              generated narrative
      Table: "Assessment area" / "Finding..."     (8 data rows, col 1)
    Heading 1: "Commercial, Performance and Renewal Assessment"
      Table: "Assessment area" / "Finding..."     (8 data rows, col 1) — second one
      Heading 2: "Significant Variations"
        List Bullet paragraphs                    one per linked non-BASE document
      Heading 2: "Consolidated Procurement Assessment"
        Table: "Category" / "Assessment"          (5 data rows, col 1) — scorecard
      Heading 2: "Recommended Actions"
        List Bullet paragraphs                    one per recommended action
    Closing "Note:" paragraph                     replaced with a fixed disclaimer

Tables are located by their first DATA row's first-column text (a stable
marker even if the template's surrounding prose changes); bullet lists are
located by the Heading 2 immediately preceding them. If the template is
edited in a way that removes one of these markers, this module raises a
clear error naming which one — silently writing into the wrong table would
be worse.
"""

import copy
import os
from typing import Dict, List, Optional

import contract_extraction
import contract_linking
from config import ProjectConfig

_TEMPLATE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "assets", "Contract_Workspace_Summary_Template.docx"
)

_DISCLAIMER = (
    "Note: This summary was generated by LEX from the contract documents linked to this "
    "CW number in Snowflake. Every finding above is grounded in the cited source document "
    "and section — verify any field not yet marked Verified before relying on it, "
    "particularly where the confidence shown is Low or Not found."
)

_NO_VARIATIONS_TEXT = "No variations, extensions, or novations are currently linked to this contract."
_NO_ACTIONS_TEXT = "No specific actions flagged."


class TemplateStructureError(Exception):
    """Raised when the bundled template doesn't have a marker this module
    expects — e.g. it was edited in a way that removed or renamed a table
    or heading this code locates by text. Deliberately loud rather than
    silently writing into the wrong place."""


def _iter_block_items(document):
    """Yields each top-level paragraph/table in document order (python-docx's
    own `.paragraphs`/`.tables` lists each type separately and lose the
    interleaving, which this module's positional logic — "the bullets right
    after this heading", "the table whose first row says X" — depends on)."""
    from docx.table import Table
    from docx.text.paragraph import Paragraph

    for child in document.element.body.iterchildren():
        if child.tag.endswith("}p"):
            yield Paragraph(child, document)
        elif child.tag.endswith("}tbl"):
            yield Table(child, document)


def _find_table_by_marker(blocks, marker_text: str):
    from docx.table import Table
    for block in blocks:
        if isinstance(block, Table) and len(block.rows) > 1:
            if block.rows[1].cells[0].text.strip() == marker_text:
                return block
    raise TemplateStructureError(
        f"Could not find a table whose first data row reads {marker_text!r} — "
        f"has the template been restructured?"
    )


def _find_heading_index(blocks, heading_text: str) -> int:
    from docx.text.paragraph import Paragraph
    for i, block in enumerate(blocks):
        if isinstance(block, Paragraph) and block.text.strip() == heading_text:
            return i
    raise TemplateStructureError(
        f"Could not find a heading paragraph reading {heading_text!r} — "
        f"has the template been restructured?"
    )


def _fill_table_column(table, values_by_marker: Dict[str, Optional[str]], col: int = 1) -> None:
    """values_by_marker: {row-1-marker-text: value}. Matches each data row
    (from row 1 on) by its own column-0 label — order-independent, so a
    template with rows reordered still fills correctly, unlike a plain
    positional fill."""
    for row in table.rows[1:]:
        marker = row.cells[0].text.strip()
        if marker in values_by_marker:
            row.cells[col].text = values_by_marker[marker] or "Not yet extracted."


def _set_single_run_text(paragraph, text: str) -> None:
    """Every placeholder paragraph this module rewrites in place (as
    opposed to cloning) has exactly one run — confirmed against the
    bundled template. Clears any extra runs defensively rather than
    assuming that holds for every future edit of the template."""
    runs = paragraph.runs
    if not runs:
        paragraph.add_run(text)
        return
    runs[0].text = text
    for extra in runs[1:]:
        extra._element.getparent().remove(extra._element)


def _replace_bullet_list(blocks, heading_index: int, items: List[str]) -> None:
    """Replaces every consecutive 'List Bullet' paragraph immediately
    following blocks[heading_index] with one bullet per item (cloning the
    first placeholder bullet's formatting/style for each), then removes
    whatever placeholder bullets are left over. items=[] renders a single
    "nothing to report" bullet rather than leaving the section empty,
    since an empty section reads as a mistake in a document like this."""
    from docx.text.paragraph import Paragraph

    bullet_indices = []
    for i in range(heading_index + 1, len(blocks)):
        block = blocks[i]
        if isinstance(block, Paragraph) and block.style and block.style.name == "List Bullet":
            bullet_indices.append(i)
        else:
            break
    if not bullet_indices:
        raise TemplateStructureError(
            f"No 'List Bullet' paragraphs found immediately after heading "
            f"{blocks[heading_index].text!r} — has the template been restructured?"
        )

    template_para = blocks[bullet_indices[0]]
    display_items = items or [_NO_ACTIONS_TEXT if "Action" in blocks[heading_index].text else _NO_VARIATIONS_TEXT]

    anchor_element = template_para._p
    for item_text in display_items:
        new_p_element = copy.deepcopy(template_para._p)
        new_paragraph = Paragraph(new_p_element, template_para._parent)
        _set_single_run_text(new_paragraph, item_text)
        anchor_element.addprevious(new_p_element)

    # Remove every original placeholder bullet paragraph (including blank
    # trailing ones the template may have, e.g. an empty final "List
    # Bullet" left over from Word's own list-formatting quirks).
    for i in bullet_indices:
        el = blocks[i]._p
        el.getparent().remove(el)


def build_contract_docx(session, project: ProjectConfig, contract_id: int) -> bytes:
    """Builds the full Contract Workspace Summary .docx for one contract
    from its already-extracted CONTRACT_FIELD_EXTRACTS / CONTRACT_REGISTER
    rows — no new Cortex calls here, purely formatting. Returns raw .docx
    bytes for st.download_button."""
    import io
    import docx

    contract = contract_linking.get_contract(session, project, contract_id)
    fields = {f["FIELD_KEY"]: f for f in contract_extraction.get_contract_fields(session, project, contract_id)}
    variations = contract_linking.get_significant_variations(session, project, contract_id)

    def value_of(field_key: str) -> Optional[str]:
        return fields.get(field_key, {}).get("FIELD_VALUE")

    document = docx.Document(_TEMPLATE_PATH)
    blocks = list(_iter_block_items(document))

    # --- Title / subtitle ---
    # CONTRACT_REGISTER.CONTRACT_TITLE (from the Required Contracts
    # Register workbook) is already in "<Supplier> - <Description>" form
    # in practice — e.g. "Siemens - Contract for Support of DTRS" — i.e.
    # already exactly what the template's title wants, so it's used as-is
    # rather than re-composed with the separately-extracted SUPPLIER field
    # (which would otherwise duplicate the supplier name in the title).
    # The extracted fields are the fallback for a contract the register
    # hasn't named yet.
    title_para = blocks[0]
    title_text = (
        contract.get("CONTRACT_TITLE")
        or f"{value_of('SUPPLIER') or contract['CW_NUMBER']} - {value_of('SERVICES') or contract['CW_NUMBER']}"
    )
    _set_single_run_text(title_para, title_text)

    # --- Contract detail table ---
    contract_detail_table = _find_table_by_marker(blocks, "Supplier")
    _fill_table_column(contract_detail_table, {
        contract_extraction.FIELD_LABELS[key]: value_of(key)
        for key in contract_extraction.CONTRACT_DETAIL_FIELDS
    })

    # --- Executive Assessment narrative + its assessment table ---
    exec_heading_idx = _find_heading_index(blocks, "Executive Assessment")
    _set_single_run_text(blocks[exec_heading_idx + 1], contract.get("OVERVIEW_SUMMARY") or "Not yet generated.")
    exec_table = _find_table_by_marker(blocks, "Novation / assignment")
    _fill_table_column(exec_table, {
        contract_extraction.FIELD_LABELS[key]: value_of(key)
        for key in contract_extraction.EXECUTIVE_ASSESSMENT_FIELDS
    })

    # --- Commercial, Performance and Renewal Assessment table ---
    commercial_table = _find_table_by_marker(blocks, "Price review")
    _fill_table_column(commercial_table, {
        contract_extraction.FIELD_LABELS[key]: value_of(key)
        for key in contract_extraction.COMMERCIAL_ASSESSMENT_FIELDS
    })

    # --- Significant Variations ---
    variations_heading_idx = _find_heading_index(blocks, "Significant Variations")
    variation_lines = []
    for v in variations:
        label = f"{v['FILE_NAME']} ({v['DOC_ROLE'].replace('_', ' ').title()}"
        label += f", {v['EFFECTIVE_DATE']})" if v.get("EFFECTIVE_DATE") else ")"
        summary = v.get("NODE_SUMMARY") or "not yet indexed"
        variation_lines.append(f"{label}: {summary}")
    _replace_bullet_list(blocks, variations_heading_idx, variation_lines)

    # --- Consolidated Procurement Assessment (classification scorecard) ---
    scorecard = contract.get("CLASSIFICATION_SCORECARD") or {}
    scorecard_table = _find_table_by_marker(blocks, "Overall classification")
    _fill_table_column(scorecard_table, {
        contract_extraction.CLASSIFICATION_SCORECARD_LABELS[key]: scorecard.get(key)
        for key in contract_extraction.CLASSIFICATION_SCORECARD_FIELDS
    })

    # --- Recommended Actions ---
    actions_heading_idx = _find_heading_index(blocks, "Recommended Actions")
    _replace_bullet_list(blocks, actions_heading_idx, contract.get("RECOMMENDED_ACTIONS") or [])

    # --- Closing disclaimer ---
    # The final "Note:" paragraph is the last block in the template.
    from docx.text.paragraph import Paragraph
    for block in reversed(blocks):
        if isinstance(block, Paragraph) and block.text.strip().startswith("Note:"):
            _set_single_run_text(block, _DISCLAIMER)
            break

    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()
