"""
pdf_report.py — build the downloadable "Contract Summary" PDF for one
contract, from its already-extracted fields (no new Cortex calls — this is
purely a formatting step over CONTRACT_FIELD_EXTRACTS / CONTRACT_REGISTER
rows the caller already fetched).

LEX-specific: not part of the generic project-llm-wiki template. Uses
fpdf2 — pure Python, no system dependencies (no wkhtmltopdf/headless
browser to install on a container-runtime compute pool) — for a plain,
readable report. The team has said they'll share example templates to
match a house style; this is a reasonable default layout to replace once
that arrives, not a final design.
"""

from datetime import datetime, timezone
from typing import Dict, List, Optional


def _pdf_safe(text: Optional[str]) -> str:
    """fpdf2's core fonts (Helvetica/Times/Courier) only support the
    cp1252 character set. LLM-generated text is usually fine (cp1252
    already covers em/en dashes, curly quotes, ellipses), but this is a
    defensive backstop against the rare character outside it (e.g. from
    an unusual contract name) so a PDF export never hard-crashes on
    encoding — it degrades to a '?' for that one character instead."""
    if not text:
        return ""
    try:
        text.encode("cp1252")
        return text
    except UnicodeEncodeError:
        return text.encode("cp1252", errors="replace").decode("cp1252")


def build_contract_pdf(cw_number: str, contract_title: Optional[str], overview: Optional[str],
                       fields: List[dict], field_labels: Dict[str, str],
                       generated_note: str = "") -> bytes:
    """fields: the list get_contract_fields() returns — dicts with
    FIELD_KEY, FIELD_VALUE, CONFIDENCE, SOURCE_FILE_NAME, IS_VERIFIED, in
    STOCK_FIELDS order. Returns raw PDF bytes for st.download_button."""
    from fpdf import FPDF

    pdf = FPDF(format="A4")
    # fpdf2's core fonts default to latin-1 (ISO-8859-1) encoding, which
    # does NOT include em/en dashes, curly quotes, or ellipses — exactly
    # the characters LLM-generated text routinely uses, and _pdf_safe()
    # above was written assuming cp1252 support. Explicitly switching to
    # cp1252 (Windows-1252), a superset of latin-1 that does include them,
    # is what actually makes _pdf_safe()'s encoding check meaningful;
    # confirmed by reproducing an UnicodeEncodeError on an em dash without
    # this line, and its absence with it, in a local smoke test — this
    # wasn't caught by static review alone.
    pdf.core_fonts_encoding = "cp1252"
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # fpdf2's multi_cell defaults to new_x=XPos.RIGHT (leaving the cursor at
    # the cell's right edge, near the page's right margin for a full-width
    # w=0 cell) rather than resetting to the left margin — confirmed by a
    # local smoke test that hit "Not enough horizontal space to render a
    # single character" on the very next multi_cell call without this.
    # Passed explicitly on every multi_cell/cell call below instead of
    # relying on the (surprising) default.
    NL = {"new_x": "LMARGIN", "new_y": "NEXT"}

    pdf.set_font("Helvetica", "B", 16)
    title = _pdf_safe(f"{cw_number} — {contract_title}" if contract_title else cw_number)
    pdf.multi_cell(0, 9, title, **NL)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(110, 110, 110)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pdf.cell(0, 6, _pdf_safe(f"Generated by LEX — {generated_at}{generated_note}"), **NL)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    if overview:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Overview", **NL)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5.5, _pdf_safe(overview), **NL)
        pdf.ln(4)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Standard questions", **NL)
    pdf.ln(1)

    for f in fields:
        label = field_labels.get(f["FIELD_KEY"], f["FIELD_KEY"])
        value = f.get("FIELD_VALUE")
        confidence = f.get("CONFIDENCE")
        source = f.get("SOURCE_FILE_NAME")
        verified = f.get("IS_VERIFIED")

        pdf.set_font("Helvetica", "B", 10.5)
        pdf.multi_cell(0, 6, _pdf_safe(label), **NL)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, _pdf_safe(value) if value else "Not yet extracted.", **NL)

        footer_bits = []
        if confidence:
            footer_bits.append(f"Confidence: {confidence}")
        if verified:
            footer_bits.append("Verified")
        if source:
            footer_bits.append(f"Source: {source}")
        if footer_bits:
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(120, 120, 120)
            pdf.multi_cell(0, 4, _pdf_safe(" · ".join(footer_bits)), **NL)
            pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    return bytes(pdf.output())
